image: node:10.15

stages:
  - install
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install dependences:
  stage: install
  script:
    - npm install

build the static:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist
  only:
    - master

build the ssr:
  stage: build
  script:
    - npm run build
    - npm run start &
    - sleep 3
  artifacts:
    paths:
      - nuxt
  only:
    - master

test static:
  image: alpine
  stage: test
  script:
    - grep -q "Michigan" ./dist/index.html
