image: node

stages:
  - Install
  - Build
  - Test
  - Deploy

Install Dependencies:
  stage: Install
  script:
  - npm install
  artifacts:
    paths:
    - ./node_modules
  
Build Site:
  stage: Build
  only:
    - master
  script:
    - npm run generate &
    - sleep 3
  artifacts:
    paths:
    - ./dist

Test Artifact:
  image: alpine
  stage: Test
  script:
    - grep "Michigan" ./dist/index.html

Deploy to Surge:
  stage: Deploy
  script:
    - npm install --global surge
    - surge --project ./dist --domain mwpanuxtgitlab.surge.sh