image: node

stages:
  - Install
  - Build
  - Test

Install Dependencies:
  stage: Install
  script:
  - npm install
  artifacts:
    paths:
    - ./node_modules
  
Build Site:
  stage: Build
  only:
    - master
  script:
    - npm run generate  
  artifacts:
    paths:
    - ./dist

Test Artifact:
  image: alpine
  stage: Test
  script:
    - grep "Michigan" ./dist/index.html
    - grep "sdjfhs;dlkfjsd" ./dist/index.html