image: node

stages:
  - install
  - build
  - test

cache:
  paths:
    - node_modules/

install dependences:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

build the project:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist
  only:
    - master

test artifacts:
  stage: test
  script:
    - grep "Michigan" ./dist/index.html
    - grep "XXXXXXXXXX" ./dist/index.html
