image: node

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

stages:
  - install
  - build
  - test
  - deploy staging
  - deploy prod
  - deployment test

Install Dependencies:
  stage: install
  script:
  - npm install
  artifacts:
    paths:
    - ./node_modules
  
Build Site:
  stage: build
  only:
    - master
  script:
    - npm run generate
  artifacts:
    paths:
    - ./dist

Test Artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Michigan" ./dist/index.html

Deploy Staging:
  stage: deploy staging
  environment:
    name: staging
    url: mwpanuxtgitlab-stage.surge.sh
  script:
    - npm install --global surge
    - surge --project ./dist --domain mwpanuxtgitlab-stage.surge.sh

Deploy Prod:
  stage: deploy prod
  environment:
    name: prod
    url: mwpanuxtgitlab.surge.sh
  script:
    - npm install --global surge
    - surge --project ./dist --domain mwpanuxtgitlab.surge.sh

Test Prod:
  stage: deployment test
  script:
  - curl "mwpanuxtgitlab.surge.sh" | tac | tac | grep -q "Michigan"