image: node

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
variables:
  STAGING_DOMAIN: mwpanuxtgitlab-stage.surge.sh
  PROD_DOMAIN: mwpanuxtgitlab.surge.sh

stages:
  - install
  - build
  - test
  - deploy staging
  - deploy prod
  - deployment test

Install Dependencies:
  stage: install
  script:
  - npm install
  artifacts:
    paths:
    - ./node_modules
  
Build Site:
  stage: build
  only:
    - master
  script:
    - npm run generate
  artifacts:
    paths:
    - ./dist

Test Artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Michigan" ./dist/index.html

Deploy Staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  script:
    - npm install --global surge
    - surge --project ./dist --domain $STAGING_DOMAIN

Deploy Prod:
  stage: deploy prod
  environment:
    name: prod
    url: http://$PROD_DOMAIN
  when: manual
  script:
    - npm install --global surge
    - surge --project ./dist --domain $PROD_DOMAIN

Test Prod:
  stage: deployment test
  script:
  - curl "$PROD_DOMAIN" | tac | tac | grep -q "Michigan"