image: node

stages:
  - build
  - start

before_script:
  - npm install

cache:
  paths:
    - node_modules/

build the project:
  stage: build
  script:
    - npm run build
    - ls
  artifacts:
    paths:
      - nuxt
    only:
      - master
