image: node

stages:
  - build
  - start

before_script:
  - npm install

cache:
  paths:
    - node_modules/

build the project:
  stage: build
  script:
    - ls
    - npm run generate
    - ls
  artifacts:
    paths:
      - dist
  only:
    - master
