image: node:10.15

stages:
  - install
  - build
  - test

cache:
  paths:
    - node_modules/

install dependences:
  stage: install
  script:
    - npm install

build the project:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist
  only:
    - master

test static:
  image: alpine
  stage: test
  script:
    - grep -q "Michigan" ./dist/index.html

test universal:
  image: node:10.15
  stage: test
  script:
    - npm install
    - npm run build -dd
    - npm run start -dd
    - curl "http://localhost:3000" | grep -q "Michigan" ./dist/index.html
