image: node

stages:
  - build
  - start

before_script:
  - npm install

cache:
  paths:
    - node_modules/

build the project:
  stage: build
  script:
    - nuxt build
    - nuxt start
    - ls
  artifacts:
    paths:
      - nuxt
  only:
    - master
